name: Directory-Specific CI/CD

on:
  push:
    paths:
      - 'FamilyVaultReact/**'
      - 'FamilyVaultCdk/**'
      - 'FamilyVaultCicd/**'

jobs:
  debug-job:
    name: DEBUG files changed
    runs-on: ubuntu-latest
    steps:
    - name: print changed files
     run: |
          echo "$GITHUB_EVENT" | jq '.commits[] | {modified: .modified, added: .added}'

  react-job:
    name: React CI/CD
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'FamilyVaultReact')
    steps:
    - name: Call React API Gateway
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.AUTHORIZATION_KEY }}" \
          -d '{"action": "trigger"}' \
          ${{ secrets.APIGATEWAY_WEBHOOK_URL }}/react

  cdk-job:
    name: CDK CI/CD
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'FamilyVaultCdk')
    steps:
    - name: Call CDK API Gateway
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.AUTHORIZATION_KEY }}" \
          -d '{"action": "trigger"}' \
          ${{ secrets.APIGATEWAY_WEBHOOK_URL }}/cdk

  cicd-job:
    name: CICD CI/CD
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'FamilyVaultCicd')
    steps:
    - name: Call CICD API Gateway
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.AUTHORIZATION_KEY }}" \
          -d '{"action": "trigger"}' \
          ${{ secrets.APIGATEWAY_WEBHOOK_URL }}/cicd
