name: Monorepo CI/CD

on:
  push:
    branches:
      - main

jobs:
  # Job to detect changes in specific paths
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      cdk-changes: ${{ steps.filter.outputs.cdk }}
      cicd-changes: ${{ steps.filter.outputs.cicd }}
      react-changes: ${{ steps.filter.outputs.react }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Paths Filter
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            cdk:
              - 'FamilyVaultCdk/**'
            cicd:
              - 'FamilyVaultCicd/**'
            react:
              - 'FamilyVaultReact/**'

  # Job to run TruffleHog scan
  trufflehog-scan:
    name: TruffleHog Enterprise scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: TruffleHog Enterprise scan
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
          args: --fail-verified ${{ github.event.repository.default_branch }} HEAD

  # CDK job
  cdk-job:
    name: CDK CI/CD
    runs-on: ubuntu-latest
    needs: [detect-changes, trufflehog-scan]
    if: ${{ needs.detect-changes.outputs.cdk-changes == 'true' }}
    steps:
      - name: Call CDK API Gateway
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.AUTHORIZATION_KEY }}" \
            -d '{"action": "trigger"}' \
            ${{ secrets.APIGATEWAY_WEBHOOK_URL }}/cdk

  # CICD job
  cicd-job:
    name: CICD CI/CD
    runs-on: ubuntu-latest
    needs: [detect-changes, trufflehog-scan]
    if: ${{ needs.detect-changes.outputs.cicd-changes == 'true' }}
    steps:
      - name: Call CICD API Gateway
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.AUTHORIZATION_KEY }}" \
            -d '{"action": "trigger"}' \
            ${{ secrets.APIGATEWAY_WEBHOOK_URL }}/cicd

  # React job
  react-job:
    name: React CI/CD
    runs-on: ubuntu-latest
    needs: [detect-changes, trufflehog-scan]
    if: ${{ needs.detect-changes.outputs.react-changes == 'true' }}
    steps:
      - name: Call React API Gateway
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.AUTHORIZATION_KEY }}" \
            -d '{"action": "trigger"}' \
            ${{ secrets.APIGATEWAY_WEBHOOK_URL }}/react
