name: Secrets Scan

on:
  push:
    branches:
      - main

jobs:
  secret_detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog-enterprise@v1
        with:
          args: "scan --ruleset=gitleaks --since-commit=$GITHUB_SHA"
